# Custom Language File for Launcher Customizer

[ejs.app]
title = "픽셀몬 스터디"

[ejs.landing]
mediaGitHubURL = "https://github.com/CustomLauncherLab/PixelmonStudy"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"
mediaSoopURL = "#"
mediaChzzkURL = "#"
screenshotsTooltip = "스크린샷"

[ejs.settings]
sourceGithubLink = "https://github.com/CustomLauncherLab/PixelmonStudy"
supportLink = "https://github.com/CustomLauncherLab/PixelmonStudy/issues"

[ejs.welcome]
welcomeHeader = "픽셀몬 스터디"
welcomeDescription = ""
welcomeDescCTA = ""